# Generated by Django 5.1.8 on 2025-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
