# Generated by Django 5.1.8 on 2025-04-03 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('lesson', 'lesson'), ('quiz', 'quiz')], max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'Curriculum Items Table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Courses Table',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='Course.course')),
            ],
            options={
                'db_table': 'Curriculums Table',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='Course.course')),
            ],
            options={
                'db_table': 'Exams Table',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('note_file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('curriculum_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='Course.curriculumitem')),
            ],
            options={
                'db_table': 'Lessons Table',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Course.exam')),
            ],
            options={
                'db_table': 'Questions Table',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Course.question')),
            ],
            options={
                'db_table': 'Answers Table',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('curriculum_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='Course.curriculumitem')),
            ],
            options={
                'db_table': 'Quizzes Table',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_options', to='Course.quiz')),
            ],
            options={
                'db_table': 'Quiz Options Table',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Course.curriculum')),
            ],
            options={
                'db_table': 'Sections Table',
            },
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='Course.section'),
        ),
    ]
